<center> <h1> Scoring crediticio </h1> </center>


<div style="text-align: right"><img src="http://static.iris.net.co/dinero/upload/images/2017/3/17/243092_1.jpg" width="500" /></div>

La cooperativa financiera FINCOOP ha definido una fórmula para otorgamiento crediticio que tiene la siguiente forma matemática:

$$ score = edad*0.2 + salario*0.3 + prestamos\_pagados*0.1 $$

El gerente desea automatizar el cálculo del score. Para ello pide al equipo de tecnología desarrollar un programa que calcule el score, teniendo en cuenta las variables de la fórmula.

El equipo define que se debe desarrollar una función en Python cuyos argumentos de entrada sean: la edad, salario y el número de prestamos pagados.


In [1]:
#Definición de variables de cliente
edad = 40
salario = 1500000
prestamos = 4

In [3]:
#Ejercicio 1
def score (edad, salario, prestamos):
    
    #Inicio de Completar ~ 1 línea
    score = edad * 0.2 + salario * 0.3 + prestamos * 0.1
    #Fin de Completar

    return score

score = score(edad, salario, prestamos)
print(score)

450008.4


Tras una charla entre los expertos, se decide crear una segunda versión de Python, la cual reciba un único vector (numpy) y realice el cálculo automáticamente.

In [7]:
#Definición de vector de entrada
import numpy as np

vector_v = np.array([edad, salario, prestamos])

vector_v[0]

40

In [9]:
#Ejercicio 2
def score_vectorizado (vector_vars):
    
    #Inicio de Completar ~ 1 línea
    score = vector_vars[0] * 0.2 + vector_vars[1] * 0.3 + vector_vars[2] * 0.1
    #Fin de Completar
    

    return score

score = score_vectorizado(vector_v)
print(score)

450008.4


El gerente anuncia en una reunión que los pesos asignados a las variables pueden cambiar, por lo que el equipo decide crear una función más general, que reciba como argumentos el vector de variables y un vector de pesos:

In [11]:
#Definición de vector de entrada y vector de pesos
vector_v = np.array([edad, salario, prestamos])
vector_p = np.array([0.2, 0.3, 0.1])

450008.4

In [12]:
#Ejercicio 3
def score_vectorizado_general (vector_vars, vector_pesos):
    
    #Inicio de Completar ~ 1 línea
    score = np.dot(vector_vars, vector_pesos)
    #Fin de Completar
    
    return score

score = score_vectorizado_general (vector_v, vector_p)
print(score)

450008.4


Ahora se debe implementar la función de tal manera que acepte a muchos clientes en forma de matriz y obtenga el score para cada uno. Cada columna corresponde a una variable y cada fila a un cliente:

$$
\begin{pmatrix}
edad\_cliente_{1} & salario\_cliente_1 & prestamos\_cliente_1 \\
edad\_cliente_2 & salario\_cliente_2 & prestamos\_cliente_2 \\
edad\_cliente_3 & salario\_cliente_3 & prestamos\_cliente_3
\end{pmatrix} $$

In [13]:
#Matriz clientes

matriz_clientes = np.matrix([[20, 780000, 0],
                             [30, 1800000, 3],
                             [25, 2000000, 4]])

In [15]:
#Ejercicio 4
def score_clientes (matriz_clientes, vector_pesos):
    
    #Inicio de Completar ~ 1 línea
    score_por_cliente = np.dot(matriz_clientes, vector_pesos)
    #Fin de Completar
    
    return score_por_cliente

score = score_clientes(matriz_clientes, vector_p)
print(score)

np.max(score)

[[234004.  540006.3 600005.4]]


600005.4

El equipo se percata que hay algunas variables que tienen más pesos que otras, por lo se desea ajustarlas. Crear una función que reciba la matriz anterior y devuelva la matriz ajustada aplicando la siguiente función a cada columna:

$$ valor = (valor-min\_columna)/(max\_columna - min\_columna) $$

In [21]:
#Ejercicio 5
def normalizar_matriz (input_matriz):
    
    #Inicio de Completar ~ 1 línea
    output_matriz = (input_matriz - np.min(input_matriz, axis=0)) / (np.max(input_matriz, axis=0) - np.min(input_matriz, axis=0))
    #Fin de Completar
    
    return output_matriz

print(normalizar_matriz(matriz_clientes))

[[0.         0.         0.        ]
 [1.         0.83606557 0.75      ]
 [0.5        1.         1.        ]]


Ahora combina todo lo anterior para crear un score final para todos los clientes normalizados.¿Qué valores deberían tener los pesos para que el score se mueva entre 0 y 1? Recalcula el valor de los pesos para que esto se cumpla.

In [30]:
#Ejercicio 6
def score_total(matriz_clientes, vector_pesos):

    #Inicio de Completar ~ 2 líneas
    vector_pesos = vector_pesos / np.sum(vector_pesos) #se normaliza el vector pesos
    score_matriz = np.dot(normalizar_matriz(matriz_clientes),vector_pesos)
    #Fin de Completar
    
    return score_matriz


print(score_total(matriz_clientes, vector_p))

[[0.         0.87636612 0.83333333]]


En Machine Learning, una de las funciones más importantes es la función sigmoide, la cual tiene la siguiente forma: Es una función de activación, la otra función de activación se llama relu

$$ simoid(x) = \frac{1}{(1+e^{-x})} $$

In [33]:
def sigmoid (x):
    
    return (1/(1+np.exp(-x)))


print(score_clientes(normalizar_matriz(matriz_clientes), vector_p))
score_modificado = sigmoid(score_clientes(normalizar_matriz(matriz_clientes), vector_p))
print(score_modificado)

[[0.         0.52581967 0.5       ]]
[[0.5        0.62850759 0.62245933]]


El score modificado resulta ser una unidad básica en el machine learning: ¡Una neurona! Profundizaremos más sobre esto en un modulo posterior.

Por último, si se toma como umbral 0.6 sobre el score modificado para otorgar los creditos, use un ciclo for sólo para imprimir el nombre de los clientes que reciben el crédito. El nombre de los clientes es dado en la lista $nombres$.

In [85]:
#Ejercicio 7
nombres = ["Juan", "Maria", "Pablo"]

#Inicio completar ~ 3 líneas

for i in range(score_modificado.shape[1]):
    if score_modificado[0,i] > 0.6:
        print('Se le a otorgado el crédito a: ' + nombres[i])
    
#Fin completar

Se le a otorgado el crédito a: Maria
Se le a otorgado el crédito a: Pablo


**Done! \o/**